### ISSUE TITLE
Anonymous : Internal server error running query

### ISSUE THREAD

**Issue by joaogarin** [drupal-graphql/graphql-metatag#3]
So I was trying out the module, everything worked really nicely. I did open a [doc PR](https://github.com/drupal-graphql/graphql/pull/619) for graphql, I think it makes sense to have "GraphqQL Documentation" all together in one place. instead of opening docs in all the subrepos.

While doing a query for metatag and talking on the slack channel found that there is an issue with the graphql_metatag module integration (perhaps its an issue with Metatag module itself)

``` 
query findJob($slug: String!) {
    route(path: $slug) {
      ... on EntityCanonicalUrl {
        entity {
          entityLabel
          entityMetatags {
            key
            value
          }
        }
      }
    }
  } 
```

returns an internal server error as an anonymous user. Couldn't find anything really relevant in the logs..at least not in db logs. I Will try and dig a bit deeper later to see if I can get some more info

**Comment by pmelab** [comment]
Not sure this is related, but I stumbled on a bug in metatag that gave me a hard time:
https://www.drupal.org/project/metatag/issues/2957411

**Comment by joaogarin** [comment]
Hm no I just tried the patch I still get the same issue so maybe not related.
